# \u8BBE\u7F6E\u6FC0\u6D3B\u7684\u73AF\u5883
spring:
  profiles:
    active: 'dev'
  mvc:
    view:
      prefix: '/templates/'
      suffix: '.ftl'
  freemarker:
    cache: false
    request-context-attribute: 'request'
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
#    password:
    pool:
      max-wait: -1
      max-idle: -1
      min-idle: -1
    timeout: 5000
#mybatis:
#  type-aliases-package: 'com.table.dao.table.entity'
#  mapper-locations: 'classpath:com/table/dao/table/*.xml'
mapper:
  mappers: com.table.util.MyMapper
  not-empty: false
  identity: 'MYSQL'
pagehelper:
  helper-dialect: 'mysql'
  reasonable: 'true'
  support-methods-arguments: 'true'
  params: 'count'
  ###################################
  ############# REDIS
  ###################################
#  # Redis数据库索引
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=127.0.0.1
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码
#  spring.redis.password=redis
#  # 连接池最大阻塞等待时间
#  spring.redis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.pool.max-idle=-1
#  # 连接池中的最小空闲连接
#  spring.redis.pool.min-idle=-1
#  # 连接超时时间
#  spring.redis.timeout=5000
##shiro:
#  loginUrl: '/login.html'
#  successUrl: '/'
#  unauthorizedUrl: 'null'
#  sessionManager:
#    sessionIdCookieEnabled: 'true'
#    sessionIdUrlRewritingEnabled: 'true'
#

